/**
 * Categorize quiz.json questions into four official taxi exam topic areas:
 * 1. assisting_passengers   — Matkustajien avustaminen ja turvallisuudesta huolehtiminen
 * 2. special_needs          — Eri matkustajaryhmien erityistarpeet
 * 3. customer_service       — Taksipalvelujen asiakaspalvelutilanteet
 * 4. traffic_safety         — Kuljetusten ja liikenneturvallisuuteen vaikuttavat tekijät
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const categoriesDir = path.join(root, 'Que Categories');
const questions = JSON.parse(fs.readFileSync(path.join(root, 'quiz.json'), 'utf8'));

const CATEGORIES = {
  assisting_passengers: {
    title: 'Assisting passengers and ensuring their safety',
    file: 'Assisting_passengers.json',
  },
  special_needs: {
    title: 'Special needs of different passenger groups',
    file: 'Special_needs.json',
  },
  customer_service: {
    title: 'Customer service situations in taxi services',
    file: 'Customer_service.json',
  },
  traffic_safety: {
    title: 'Factors affecting transport and traffic safety',
    file: 'Traffic_safety.json',
  },
};

/** Explicit per-question assignments (reviewed against question content). */
const BY_ID = {
  // Assisting passengers and ensuring their safety (39)
  9: 'assisting_passengers',
  10: 'assisting_passengers',
  11: 'assisting_passengers',
  19: 'assisting_passengers',
  31: 'assisting_passengers',
  41: 'assisting_passengers',
  43: 'assisting_passengers',
  51: 'assisting_passengers',
  52: 'assisting_passengers',
  57: 'assisting_passengers',
  60: 'assisting_passengers',
  61: 'assisting_passengers',
  64: 'assisting_passengers',
  66: 'assisting_passengers',
  69: 'assisting_passengers',
  72: 'assisting_passengers',
  77: 'assisting_passengers',
  80: 'assisting_passengers',
  85: 'assisting_passengers',
  86: 'assisting_passengers',
  159: 'assisting_passengers',
  186: 'assisting_passengers',
  204: 'assisting_passengers',
  206: 'assisting_passengers',
  209: 'assisting_passengers',
  212: 'assisting_passengers',
  213: 'assisting_passengers',
  221: 'assisting_passengers',
  229: 'assisting_passengers',
  235: 'assisting_passengers',
  236: 'assisting_passengers',
  240: 'assisting_passengers',
  242: 'assisting_passengers',
  244: 'assisting_passengers',
  246: 'assisting_passengers',
  270: 'assisting_passengers',
  273: 'assisting_passengers',
  277: 'assisting_passengers',
  292: 'assisting_passengers',

  // Special needs of different passenger groups (121)
  4: 'special_needs',
  5: 'special_needs',
  6: 'special_needs',
  7: 'special_needs',
  12: 'special_needs',
  13: 'special_needs',
  14: 'special_needs',
  15: 'special_needs',
  16: 'special_needs',
  17: 'special_needs',
  18: 'special_needs',
  23: 'special_needs',
  24: 'special_needs',
  25: 'special_needs',
  26: 'special_needs',
  27: 'special_needs',
  28: 'special_needs',
  29: 'special_needs',
  30: 'special_needs',
  32: 'special_needs',
  33: 'special_needs',
  34: 'special_needs',
  35: 'special_needs',
  36: 'special_needs',
  37: 'special_needs',
  38: 'special_needs',
  39: 'special_needs',
  40: 'special_needs',
  42: 'special_needs',
  46: 'special_needs',
  48: 'special_needs',
  49: 'special_needs',
  53: 'special_needs',
  54: 'special_needs',
  55: 'special_needs',
  62: 'special_needs',
  63: 'special_needs',
  65: 'special_needs',
  67: 'special_needs',
  68: 'special_needs',
  70: 'special_needs',
  75: 'special_needs',
  76: 'special_needs',
  78: 'special_needs',
  79: 'special_needs',
  81: 'special_needs',
  88: 'special_needs',
  89: 'special_needs',
  90: 'special_needs',
  91: 'special_needs',
  92: 'special_needs',
  93: 'special_needs',
  103: 'special_needs',
  136: 'special_needs',
  137: 'special_needs',
  139: 'special_needs',
  144: 'special_needs',
  162: 'special_needs',
  163: 'special_needs',
  165: 'special_needs',
  166: 'special_needs',
  167: 'special_needs',
  168: 'special_needs',
  169: 'special_needs',
  170: 'special_needs',
  171: 'special_needs',
  172: 'special_needs',
  173: 'special_needs',
  174: 'special_needs',
  175: 'special_needs',
  176: 'special_needs',
  177: 'special_needs',
  178: 'special_needs',
  179: 'special_needs',
  180: 'special_needs',
  182: 'special_needs',
  185: 'special_needs',
  202: 'special_needs',
  207: 'special_needs',
  208: 'special_needs',
  210: 'special_needs',
  215: 'special_needs',
  218: 'special_needs',
  219: 'special_needs',
  220: 'special_needs',
  222: 'special_needs',
  223: 'special_needs',
  224: 'special_needs',
  225: 'special_needs',
  226: 'special_needs',
  227: 'special_needs',
  228: 'special_needs',
  230: 'special_needs',
  231: 'special_needs',
  232: 'special_needs',
  233: 'special_needs',
  234: 'special_needs',
  237: 'special_needs',
  239: 'special_needs',
  248: 'special_needs',
  254: 'special_needs',
  255: 'special_needs',
  256: 'special_needs',
  257: 'special_needs',
  258: 'special_needs',
  259: 'special_needs',
  261: 'special_needs',
  262: 'special_needs',
  263: 'special_needs',
  264: 'special_needs',
  265: 'special_needs',
  266: 'special_needs',
  267: 'special_needs',
  268: 'special_needs',
  269: 'special_needs',
  271: 'special_needs',
  272: 'special_needs',
  274: 'special_needs',
  275: 'special_needs',
  276: 'special_needs',
  287: 'special_needs',

  // Customer service situations in taxi services (61)
  8: 'customer_service',
  20: 'customer_service',
  21: 'customer_service',
  44: 'customer_service',
  45: 'customer_service',
  47: 'customer_service',
  58: 'customer_service',
  59: 'customer_service',
  71: 'customer_service',
  73: 'customer_service',
  74: 'customer_service',
  83: 'customer_service',
  87: 'customer_service',
  100: 'customer_service',
  102: 'customer_service',
  111: 'customer_service',
  112: 'customer_service',
  115: 'customer_service',
  123: 'customer_service',
  127: 'customer_service',
  131: 'customer_service',
  132: 'customer_service',
  133: 'customer_service',
  141: 'customer_service',
  143: 'customer_service',
  145: 'customer_service',
  158: 'customer_service',
  161: 'customer_service',
  164: 'customer_service',
  183: 'customer_service',
  184: 'customer_service',
  187: 'customer_service',
  188: 'customer_service',
  190: 'customer_service',
  191: 'customer_service',
  192: 'customer_service',
  193: 'customer_service',
  194: 'customer_service',
  196: 'customer_service',
  199: 'customer_service',
  201: 'customer_service',
  203: 'customer_service',
  205: 'customer_service',
  214: 'customer_service',
  217: 'customer_service',
  245: 'customer_service',
  247: 'customer_service',
  249: 'customer_service',
  250: 'customer_service',
  253: 'customer_service',
  260: 'customer_service',
  278: 'customer_service',
  279: 'customer_service',
  285: 'customer_service',
  286: 'customer_service',
  294: 'customer_service',
  295: 'customer_service',
  297: 'customer_service',
  303: 'customer_service',
  307: 'customer_service',
  309: 'customer_service',
  310: 'special_needs',

  // Factors affecting transport and traffic safety (88)
  1: 'traffic_safety',
  2: 'traffic_safety',
  3: 'traffic_safety',
  22: 'traffic_safety',
  50: 'traffic_safety',
  56: 'traffic_safety',
  82: 'traffic_safety',
  84: 'traffic_safety',
  94: 'traffic_safety',
  95: 'traffic_safety',
  96: 'traffic_safety',
  97: 'traffic_safety',
  98: 'traffic_safety',
  99: 'traffic_safety',
  101: 'traffic_safety',
  104: 'traffic_safety',
  105: 'traffic_safety',
  106: 'traffic_safety',
  107: 'traffic_safety',
  108: 'traffic_safety',
  109: 'traffic_safety',
  110: 'traffic_safety',
  113: 'traffic_safety',
  114: 'traffic_safety',
  116: 'traffic_safety',
  117: 'traffic_safety',
  118: 'traffic_safety',
  119: 'traffic_safety',
  120: 'traffic_safety',
  121: 'traffic_safety',
  122: 'traffic_safety',
  124: 'traffic_safety',
  125: 'traffic_safety',
  126: 'traffic_safety',
  128: 'traffic_safety',
  129: 'traffic_safety',
  130: 'traffic_safety',
  134: 'traffic_safety',
  135: 'traffic_safety',
  138: 'traffic_safety',
  140: 'traffic_safety',
  142: 'traffic_safety',
  146: 'traffic_safety',
  147: 'traffic_safety',
  148: 'traffic_safety',
  149: 'traffic_safety',
  150: 'traffic_safety',
  151: 'traffic_safety',
  152: 'traffic_safety',
  153: 'traffic_safety',
  154: 'traffic_safety',
  155: 'traffic_safety',
  156: 'traffic_safety',
  157: 'traffic_safety',
  160: 'traffic_safety',
  181: 'traffic_safety',
  189: 'traffic_safety',
  195: 'traffic_safety',
  197: 'traffic_safety',
  198: 'traffic_safety',
  200: 'traffic_safety',
  211: 'traffic_safety',
  216: 'traffic_safety',
  238: 'traffic_safety',
  241: 'traffic_safety',
  243: 'traffic_safety',
  251: 'traffic_safety',
  252: 'traffic_safety',
  280: 'traffic_safety',
  281: 'traffic_safety',
  282: 'traffic_safety',
  283: 'traffic_safety',
  284: 'traffic_safety',
  288: 'traffic_safety',
  289: 'traffic_safety',
  290: 'traffic_safety',
  291: 'traffic_safety',
  293: 'traffic_safety',
  296: 'traffic_safety',
  298: 'traffic_safety',
  299: 'traffic_safety',
  300: 'traffic_safety',
  301: 'traffic_safety',
  302: 'traffic_safety',
  304: 'traffic_safety',
  305: 'traffic_safety',
  306: 'traffic_safety',
  308: 'traffic_safety',
};

function categorize(question) {
  return BY_ID[question.id] || null;
}

const buckets = {
  assisting_passengers: [],
  special_needs: [],
  customer_service: [],
  traffic_safety: [],
  unassigned: [],
};

for (const q of questions) {
  const cat = categorize(q);
  if (cat) buckets[cat].push(q);
  else buckets.unassigned.push(q);
}

if (buckets.unassigned.length) {
  console.error('Unassigned question IDs:', buckets.unassigned.map((q) => q.id).join(', '));
  process.exit(1);
}

const total = questions.length;
const sum = Object.keys(CATEGORIES).reduce((n, key) => n + buckets[key].length, 0);
if (sum !== total) {
  console.error(`Count mismatch: ${sum} categorized vs ${total} total`);
  process.exit(1);
}

for (const [key, meta] of Object.entries(CATEGORIES)) {
  const list = buckets[key].sort((a, b) => a.id - b.id);
  const outPath = path.join(categoriesDir, meta.file);
  fs.writeFileSync(outPath, JSON.stringify(list, null, 2) + '\n', 'utf8');
  console.log(`${meta.file}: ${list.length} questions`);
}

console.log(`Total: ${total} questions across 4 files`);
